"""empty message

Revision ID: 1d565be91098
Revises: 
Create Date: 2018-02-23 12:15:14.697023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d565be91098'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=True)
    op.create_table('project_tree',
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('children_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['children_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['project.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_tree')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
